# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file for details on configuring this file
version: 2
# registries:
#   # https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/manage-your-dependency-security/configure-access-to-private-registries#git
#   github:
#     type: git
#     url: https://github.com/
#     username: x-access-token
#     password: ${{ secrets.GH_PAT_DEPENDABOT }}
updates:
  # https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/manage-your-dependency-security/customizing-dependabot-security-prs
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '.github/actions/**'
    schedule:
      # interval: "monthly"
      # day: "friday"
      # internal: "daily" # Can be daily, weekly, or monthly
      interval: 'weekly'
      timezone: 'America/Chicago'
    commit-message:
      prefix: 'ci'
      include: 'scope' # Automatically appends "(deps)" -> ci(deps):
    labels: ['dependencies', 'deps:github-actions']
    assignees: ['andrewhaller']
    open-pull-requests-limit: 5 # Limits active PRs to prevent noise
    rebase-strategy: 'auto'
  # - package-ecosystem: 'npm'
  #   directory: '/'
  #   schedule:
  #     interval: 'weekly'
  #     timezone: 'America/Chicago'
  #   ignore:
  #     - dependency-name: '*'
  #       update-types: ['version-update:semver-major']
  #   commit-message:
  #     prefix: "chore"
  #     include: "scope" # Automatically appends "(deps)" -> chore(deps):
  #   labels: ['dependencies', 'deps:javascript']
  #   groups:
  #     npm:
  #       applies-to: version-updates
  #       patterns:
  #         - '*'
  #   open-pull-requests-limit: 5
  #   rebase-strategy: 'auto'
  # - package-ecosystem: 'pip'
  #   directory: '/src/'
  #   schedule:
  #     interval: 'weekly'
  #     timezone: 'America/Chicago'
  #   commit-message:
  #     prefix: "chore"
  #     include: "scope" # Automatically appends "(deps)" -> chore(deps):
  #   labels: ['dependencies', 'deps:python']
  #   assignees: ['andrewhaller']
  #   open-pull-requests-limit: 5
  #   rebase-strategy: 'auto'
  # - package-ecosystem: 'docker'
  #   directory: '/docker/'
  #   schedule:
  #     interval: 'weekly'
  #     timezone: 'America/Chicago'
  #   commit-message:
  #     prefix: "chore"
  #     include: "scope" # Automatically appends "(deps)" -> chore(deps):
  #   labels: ['dependencies', 'deps:docker']
  #   assignees: ['andrewhaller']
  #   open-pull-requests-limit: 5
  #   rebase-strategy: 'auto'
  # - package-ecosystem: 'terraform'
  #   directories:
  #     - '/terraform/'
  #     - '/infra/**'
  #   schedule:
  #     interval: 'weekly'
  #     timezone: 'America/Chicago'
  #   commit-message:
  #     prefix: "chore"
  #     include: "scope" # Automatically appends "(deps)" -> chore(deps):
  #   labels: ['dependencies', 'deps:terraform']
  #   assignees: ['andrewhaller']
  #   open-pull-requests-limit: 5
  #   rebase-strategy: 'auto'
