name: CI

on:
  push:
    # Fires when a tag matching v* is pushed with personal credentials.
    tags: ['v*']
    branches: [main]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:
    inputs:
      fail-on-no-release:
        description: 'Fail the workflow if no release is published (e.g. if there are no relevant commits).'
        type: boolean
        required: false
        default: true
      publish:
        description: 'Whether to run in publish mode.'
        type: boolean
        required: false
        default: false

concurrency:
  group: '${{ github.repository_id }}-${{ github.ref_name }}'
  cancel-in-progress: true

# Use PAT instead of GITHUB_TOKEN to cause semantic-release to trigger tag pipeline when tag is created.
# 'Fine-grained token' repo permissions: Contents

jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/heads/main') && ! inputs.publish
    uses: ./.github/workflows/release.yaml
    with:
      # dispatch-workflow: publish.yaml
      fail-on-no-release: ${{ inputs.fail-on-no-release || false }}
    secrets:
      github-token: ${{ secrets.GH_PAT_CREATE_RELEASE }}

  publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/v') || inputs.publish
    uses: ./.github/workflows/publish.yaml
    with:
      tag: ${{ github.ref_name }}
    secrets:
      github-token: ${{ secrets.GH_PAT_CREATE_RELEASE }}

  update-majorver:
    name: Update Major Version Tag
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: nowactions/update-majorver@v1
