name: Conventional Commit Check

on:
  pull_request:
    branches: [main]

jobs:
  conventional-commit:
    name: Run conventional commit check
    uses: stairwaytowonderland/actions/.github/workflows/conventional-commit.yaml@v1
