name: Create Labels

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        required: false
        type: boolean
        default: true
      update-existing:
        description: 'Whether to update existing labels (e.g. rename, change color/description).'
        required: false
        type: boolean
      # ref:
      #   description: 'Git ref of the shared actions repo to use (e.g. main or a specific tag/commit)'
      #   required: false
      #   type: string
      #   default: 'v1'

  workflow_run:
    workflows: ['_']
    types: [completed]

jobs:
  create-labels:
    name: Create Labels
    # if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    uses: stairwaytowonderland/actions/.github/workflows/create-labels.yaml@v1
    with:
      # ref: ${{ inputs.ref }}
      dry-run: ${{ inputs.dry-run || github.event.workflow_run.conclusion != 'success' }}
      update-existing: ${{ inputs.update-existing || false }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
