name: Import Issues from CSV

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        type: boolean
        default: true

      csv-path:
        description: 'Path (relative) to the CSV file'
        type: string
        default: 'TODO.csv'

jobs:
  import-issues:
    name: Import Issues
    uses: stairwaytowonderland/issue-management/.github/workflows/import-csv-issues.yaml@v1
    secrets:
      github-token: ${{ secrets.GH_PAT_CREATE_ISSUE }}
    with:
      batch: true
      csv-path: ${{ inputs.csv-path }}
      dry-run: ${{ inputs.dry-run }}
