name: Import Issues from CSV

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        required: true
        type: boolean
        default: true

      csv-path:
        description: 'Path (relative) to the CSV file'
        required: true
        type: string
        default: 'TODO.csv'

      # ref:
      #   description: 'Git ref of the shared actions repo to use (e.g. main or a specific tag/commit)'
      #   required: false
      #   type: string
      #   default: 'v1'

jobs:
  import-issues:
    name: Import Issues
    uses: stairwaytowonderland/actions/.github/workflows/import-csv-issues.yaml@v1
    secrets:
      github-token: ${{ secrets.GH_PAT_CREATE_ISSUE }}
    with:
      # ref: ${{ inputs.ref }}
      batch: true
      csv-path: ${{ inputs.csv-path }}
      dry-run: ${{ inputs.dry-run }}
