name: Import Issues from CSV

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      # secret-token-name:
      #   description: 'Name of the repository secret containing the GitHub Personal Access Token with permissions to create issues (e.g. GH_PAT_CREATE_ISSUE)'
      #   required: true
      #   type: string
      #   default: 'GH_PAT_CREATE_ISSUE'

      dry-run:
        description: 'Dry run'
        required: true
        type: boolean
        default: true

      csv-path:
        description: 'Path (relative) to the CSV file'
        required: true
        type: string
        default: 'TODO.csv'

jobs:
  import-issues:
    name: Import Issues
    uses: stairwaytowonderland/actions/.github/workflows/import-csv-issues.yaml@v1.30.0
    secrets:
      # github-token: ${{ secrets[inputs.secret-token-name] }}
      github-token: ${{ secrets.GH_PAT_CREATE_ISSUE }}
    with:
      ref: 'v1.30.0'
      batch: true
      csv-path: ${{ inputs.csv-path }}
      dry-run: ${{ inputs.dry-run }}
