name: Release a Version

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    name: Release
    uses: stairwaytowonderland/create-release/.github/workflows/release.yaml@v1.11.0
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
