name: 🚀 Repository Created

permissions:
  contents: read

on:
  repository_dispatch:
    types: [repository-created]

jobs:
  on-create:
    name: Repository Created
    uses: stairwaytowonderland/actions/.github/workflows/repository-dispatched.yaml@v1
    with:
      repo: ${{ github.event.client_payload.repository.name }}
      url: ${{ github.event.client_payload.repository.url }}
      sender: ${{ github.event.client_payload.sender.login }}
      sender-id: ${{ github.event.client_payload.sender.id }}
      first-commit-only: true
