name: Handle New Repository

on:
  repository_dispatch:
    types: [repository-created]

jobs:
  on-create:
    runs-on: ubuntu-latest
    steps:
      - name: Print Repository Details
        run: |
          echo "A new repository was created!"
          echo "Name: $CREATED_REPO_NAME"
          echo "Repository URL: $CREATED_REPO_URL"
          echo "Sender: $SENDER_REPO"
        env:
          CREATED_REPO_NAME: ${{ github.event.client_payload.repository.name }}
          CREATED_REPO_URL: ${{ github.event.client_payload.repository.url }}
          SENDER_REPO: ${{ toJSON(github.event.client_payload.sender) }}
