name: Watchers

on:
  watch:
    types: [started]

jobs:
  on-watch:
    name: Watching the watchers
    runs-on: ubuntu-latest
    # if: ${{ github.repository == format('{0}/repository-template', github.repository_owner) }}
    steps:
      - name: Watchers Action
        uses: stairwaytowonderland/actions/.github/actions/watchers@v1
        with:
          github-token: ${{ secrets.GH_PAT_REPO_WRITE }}
          # create-issue: true
